
export interface Job {
  id: string;
  title: string;
  companyName: string;
  companyLogoUrl?: string;
  dataAihint?: string; // Corrected: dataAihint instead of dataAihint for consistency
  location: string;
  salary?: string;
  shortDescription: string;
  tags: string[];
  postedDate: string;
}

export interface Application {
  id: string;
  jobTitle: string;
  companyName: string;
  status: 'Applied' | 'Interviewing' | 'Offer' | 'Rejected' | 'Withdrawn';
  appliedDate: string;
  jobId: string;
}

export const placeholderJobs: Job[] = [
  {
    id: '1',
    title: 'Software Engineer, Frontend',
    companyName: 'Innovatech Solutions',
    companyLogoUrl: 'https://placehold.co/100x100/008080/FFFFFF.png?text=IS',
    dataAihint: 'tech company',
    location: 'San Francisco, CA',
    salary: '$120,000 - $150,000',
    shortDescription: 'Join our dynamic team to build cutting-edge web applications using React and Next.js. Drive innovation in user experience.',
    tags: ['React', 'Next.js', 'TypeScript', 'Frontend'],
    postedDate: '2024-07-20',
  },
  {
    id: '2',
    title: 'Product Manager',
    companyName: 'FutureGadgets Inc.',
    companyLogoUrl: 'https://placehold.co/100x100/FFD700/000000.png?text=FG',
    dataAihint: 'gadget startup',
    location: 'New York, NY',
    salary: '$130,000 - $160,000',
    shortDescription: 'Lead the product vision and strategy for our innovative consumer electronics. Work closely with engineering and design teams.',
    tags: ['Product Management', 'Agile', 'SaaS', 'Mobile'],
    postedDate: '2024-07-18',
  },
  {
    id: '3',
    title: 'UX/UI Designer',
    companyName: 'Creative Minds Co.',
    companyLogoUrl: 'https://placehold.co/100x100/6A5ACD/FFFFFF.png?text=CM',
    dataAihint: 'design agency',
    location: 'Remote',
    shortDescription: 'Design beautiful and intuitive user interfaces for web and mobile applications. Portfolio required.',
    tags: ['UX', 'UI', 'Figma', 'Adobe XD', 'Mobile Design'],
    postedDate: '2024-07-22',
  },
   {
    id: '4',
    title: 'Data Scientist',
    companyName: 'Alpha Analytics',
    companyLogoUrl: 'https://placehold.co/100x100/A0A0A0/FFFFFF.png?text=AA',
    dataAihint: 'data company',
    location: 'Austin, TX',
    salary: '$110,000 - $140,000',
    shortDescription: 'Analyze large datasets to extract meaningful insights and build predictive models. Strong Python and SQL skills needed.',
    tags: ['Machine Learning', 'Python', 'SQL', 'Statistics'],
    postedDate: '2024-07-15',
  },
  {
    id: '5',
    title: 'DevOps Engineer',
    companyName: 'CloudNine Hosting',
    companyLogoUrl: 'https://placehold.co/100x100/4682B4/FFFFFF.png?text=CH',
    dataAihint: 'cloud hosting',
    location: 'Seattle, WA (Hybrid)',
    shortDescription: 'Manage and scale our cloud infrastructure using AWS, Kubernetes, and Terraform. Focus on automation and reliability.',
    tags: ['AWS', 'Kubernetes', 'Terraform', 'CI/CD'],
    postedDate: '2024-07-21',
  },
   {
    id: '6',
    title: 'Marketing Specialist',
    companyName: 'GrowthHackers Ltd.',
    companyLogoUrl: 'https://placehold.co/100x100/F08080/FFFFFF.png?text=GH',
    dataAihint: 'marketing agency',
    location: 'Remote',
    salary: '$70,000 - $90,000',
    shortDescription: 'Develop and execute digital marketing campaigns across various channels. Experience with SEO, SEM, and social media marketing.',
    tags: ['Digital Marketing', 'SEO', 'Social Media', 'Content Creation'],
    postedDate: '2024-07-19',
  },
  // Added Jobs
  {
    id: '7',
    title: 'Full Stack Developer',
    companyName: 'Tech Solutions Global',
    companyLogoUrl: 'https://placehold.co/100x100/3CB371/FFFFFF.png?text=TS',
    dataAihint: 'software development',
    location: 'Boston, MA',
    salary: '$115,000 - $145,000',
    shortDescription: 'Seeking a versatile Full Stack Developer proficient in Node.js, React, and database management.',
    tags: ['Node.js', 'React', 'MongoDB', 'Express.js'],
    postedDate: '2024-07-23',
  },
  {
    id: '8',
    title: 'Cybersecurity Analyst',
    companyName: 'SecureNet Corp',
    companyLogoUrl: 'https://placehold.co/100x100/FF6347/FFFFFF.png?text=SN',
    dataAihint: 'security firm',
    location: 'Washington D.C.',
    salary: '$90,000 - $120,000',
    shortDescription: 'Monitor security threats, perform vulnerability assessments, and implement security protocols.',
    tags: ['Cybersecurity', 'SIEM', 'Penetration Testing', 'Incident Response'],
    postedDate: '2024-07-22',
  },
  {
    id: '9',
    title: 'Cloud Architect',
    companyName: 'SkyHigh Cloud Services',
    companyLogoUrl: 'https://placehold.co/100x100/87CEEB/000000.png?text=SC',
    dataAihint: 'cloud services',
    location: 'Dallas, TX',
    shortDescription: 'Design and implement scalable and resilient cloud solutions on AWS, Azure, or GCP.',
    tags: ['Cloud Computing', 'AWS', 'Azure', 'GCP', 'Solution Architecture'],
    postedDate: '2024-07-20',
  },
  {
    id: '10',
    title: 'Mobile App Developer (iOS)',
    companyName: 'AppMakers United',
    companyLogoUrl: 'https://placehold.co/100x100/DDA0DD/000000.png?text=AU',
    dataAihint: 'app development',
    location: 'Cupertino, CA (Hybrid)',
    salary: '$125,000 - $155,000',
    shortDescription: 'Develop and maintain high-quality iOS applications using Swift and SwiftUI.',
    tags: ['iOS', 'Swift', 'SwiftUI', 'Mobile Development'],
    postedDate: '2024-07-18',
  },
  {
    id: '11',
    title: 'Business Analyst',
    companyName: 'Insightful Corp',
    companyLogoUrl: 'https://placehold.co/100x100/20B2AA/FFFFFF.png?text=IC',
    dataAihint: 'consulting firm',
    location: 'Chicago, IL',
    salary: '$80,000 - $100,000',
    shortDescription: 'Bridge the gap between business needs and technology solutions by gathering requirements and analyzing processes.',
    tags: ['Business Analysis', 'Agile', 'Requirements Gathering', 'SQL'],
    postedDate: '2024-07-16',
  },
  {
    id: '12',
    title: 'AI/ML Engineer',
    companyName: 'IntelliSys AI',
    companyLogoUrl: 'https://placehold.co/100x100/BA55D3/FFFFFF.png?text=IA',
    dataAihint: 'artificial intelligence',
    location: 'Palo Alto, CA',
    shortDescription: 'Develop and deploy machine learning models for various applications. Experience with TensorFlow or PyTorch.',
    tags: ['AI', 'Machine Learning', 'Python', 'TensorFlow', 'PyTorch'],
    postedDate: '2024-07-24',
  },
  {
    id: '13',
    title: 'Database Administrator',
    companyName: 'DataKeepers Inc.',
    companyLogoUrl: 'https://placehold.co/100x100/778899/FFFFFF.png?text=DK',
    dataAihint: 'data management',
    location: 'Remote',
    salary: '$95,000 - $115,000',
    shortDescription: 'Manage, monitor, and maintain company databases to ensure high availability and performance.',
    tags: ['DBA', 'SQL Server', 'Oracle', 'MySQL', 'Database Management'],
    postedDate: '2024-07-17',
  },
  {
    id: '14',
    title: 'Network Engineer',
    companyName: 'ConnectFast Networks',
    companyLogoUrl: 'https://placehold.co/100x100/FFA07A/000000.png?text=CN',
    dataAihint: 'networking company',
    location: 'Denver, CO',
    shortDescription: 'Design, implement, and manage network infrastructure. Cisco certifications are a plus.',
    tags: ['Networking', 'Cisco', 'Routing', 'Switching', 'Security'],
    postedDate: '2024-07-14',
  },
  {
    id: '15',
    title: 'Technical Writer',
    companyName: 'DocuPerfect Solutions',
    companyLogoUrl: 'https://placehold.co/100x100/B0C4DE/000000.png?text=DS',
    dataAihint: 'documentation service',
    location: 'Remote',
    salary: '$65,000 - $85,000',
    shortDescription: 'Create clear and concise technical documentation for software products and APIs.',
    tags: ['Technical Writing', 'Documentation', 'API', 'Markdown'],
    postedDate: '2024-07-19',
  },
  {
    id: '16',
    title: 'QA Engineer (Automation)',
    companyName: 'QualityFirst Labs',
    companyLogoUrl: 'https://placehold.co/100x100/98FB98/000000.png?text=QL',
    dataAihint: 'quality assurance',
    location: 'Raleigh, NC',
    shortDescription: 'Develop and execute automated test scripts to ensure software quality. Experience with Selenium or Cypress.',
    tags: ['QA', 'Automation Testing', 'Selenium', 'Cypress', 'Agile'],
    postedDate: '2024-07-21',
  },
  {
    id: '17',
    title: 'Frontend Developer (Vue.js)',
    companyName: 'VueVanguard Ltd.',
    companyLogoUrl: 'https://placehold.co/100x100/40E0D0/000000.png?text=VV',
    dataAihint: 'software house',
    location: 'Berlin, Germany (Remote options)',
    salary: '€60,000 - €80,000',
    shortDescription: 'Build interactive and responsive user interfaces using Vue.js and its ecosystem.',
    tags: ['Vue.js', 'JavaScript', 'Frontend', 'Nuxt.js'],
    postedDate: '2024-07-25',
  },
  {
    id: '18',
    title: 'Backend Developer (Python/Django)',
    companyName: 'Pyramid Systems',
    companyLogoUrl: 'https://placehold.co/100x100/FFDAB9/000000.png?text=PS',
    dataAihint: 'python development',
    location: 'London, UK',
    shortDescription: 'Develop robust backend services and APIs using Python and Django framework.',
    tags: ['Python', 'Django', 'REST API', 'Backend'],
    postedDate: '2024-07-13',
  },
  {
    id: '19',
    title: 'Sales Development Representative',
    companyName: 'LeadGen Experts',
    companyLogoUrl: 'https://placehold.co/100x100/CD5C5C/FFFFFF.png?text=LE',
    dataAihint: 'sales company',
    location: 'Atlanta, GA',
    salary: '$50,000 - $65,000 + Commission',
    shortDescription: 'Generate and qualify leads for the sales team through outbound prospecting.',
    tags: ['Sales', 'SDR', 'Lead Generation', 'CRM'],
    postedDate: '2024-07-20',
  },
  {
    id: '20',
    title: 'Human Resources Manager',
    companyName: 'PeopleFirst Corp',
    companyLogoUrl: 'https://placehold.co/100x100/F0E68C/000000.png?text=PC',
    dataAihint: 'hr services',
    location: 'Chicago, IL',
    shortDescription: 'Oversee all aspects of HR operations including recruitment, employee relations, and compliance.',
    tags: ['HR', 'Recruitment', 'Employee Relations', 'HR Management'],
    postedDate: '2024-07-15',
  },
  {
    id: '21',
    title: 'Content Strategist',
    companyName: 'StoryWeavers Agency',
    companyLogoUrl: 'https://placehold.co/100x100/E6E6FA/000000.png?text=SA',
    dataAihint: 'content agency',
    location: 'Remote',
    salary: '$75,000 - $95,000',
    shortDescription: 'Develop and execute content strategies to engage target audiences and achieve marketing goals.',
    tags: ['Content Strategy', 'SEO', 'Copywriting', 'Digital Marketing'],
    postedDate: '2024-07-22',
  },
  {
    id: '22',
    title: 'Game Developer (Unity)',
    companyName: 'PixelPlay Studios',
    companyLogoUrl: 'https://placehold.co/100x100/9370DB/FFFFFF.png?text=PS',
    dataAihint: 'game studio',
    location: 'Los Angeles, CA',
    shortDescription: 'Create engaging games using Unity engine. Strong C# skills required.',
    tags: ['Game Development', 'Unity', 'C#', '3D Modeling'],
    postedDate: '2024-07-18',
  },
  {
    id: '23',
    title: 'IT Support Specialist',
    companyName: 'HelpDesk Heroes',
    companyLogoUrl: 'https://placehold.co/100x100/00CED1/000000.png?text=HH',
    dataAihint: 'it support',
    location: 'Austin, TX (On-site)',
    salary: '$55,000 - $70,000',
    shortDescription: 'Provide technical support to end-users, troubleshoot hardware and software issues.',
    tags: ['IT Support', 'Help Desk', 'Troubleshooting', 'Windows', 'MacOS'],
    postedDate: '2024-07-16',
  },
  {
    id: '24',
    title: 'Financial Analyst',
    companyName: 'Capital Insights Group',
    companyLogoUrl: 'https://placehold.co/100x100/32CD32/FFFFFF.png?text=CI',
    dataAihint: 'finance company',
    location: 'New York, NY',
    shortDescription: 'Perform financial modeling, analysis, and reporting to support business decisions.',
    tags: ['Finance', 'Financial Analysis', 'Excel', 'Modeling'],
    postedDate: '2024-07-23',
  },
  {
    id: '25',
    title: 'Scrum Master',
    companyName: 'AgileFlow Solutions',
    companyLogoUrl: 'https://placehold.co/100x100/FF4500/FFFFFF.png?text=AF',
    dataAihint: 'agile consultancy',
    location: 'Remote',
    salary: '$100,000 - $130,000',
    shortDescription: 'Facilitate Scrum ceremonies, remove impediments, and coach teams on Agile practices.',
    tags: ['Scrum Master', 'Agile', 'Jira', 'Coaching'],
    postedDate: '2024-07-19',
  },
  {
    id: '26',
    title: 'Solutions Architect',
    companyName: 'ArchTech Innovations',
    companyLogoUrl: 'https://placehold.co/100x100/1E90FF/FFFFFF.png?text=AI',
    dataAihint: 'tech solutions',
    location: 'San Jose, CA',
    shortDescription: 'Design complex technical solutions for enterprise clients, aligning technology with business goals.',
    tags: ['Solution Architecture', 'Enterprise Software', 'Cloud', 'Pre-sales'],
    postedDate: '2024-07-20',
  },
  {
    id: '27',
    title: 'Digital Project Manager',
    companyName: 'PixelPerfect Projects',
    companyLogoUrl: 'https://placehold.co/100x100/DA70D6/000000.png?text=PP',
    dataAihint: 'project management',
    location: 'Remote',
    salary: '$85,000 - $110,000',
    shortDescription: 'Manage the lifecycle of digital projects, ensuring they are delivered on time and within budget.',
    tags: ['Project Management', 'Digital Marketing', 'Agile', 'Client Communication'],
    postedDate: '2024-07-17',
  },
  {
    id: '28',
    title: 'Systems Administrator',
    companyName: 'InfraCore Systems',
    companyLogoUrl: 'https://placehold.co/100x100/8FBC8F/000000.png?text=IS',
    dataAihint: 'it infrastructure',
    location: 'Phoenix, AZ',
    shortDescription: 'Maintain and administer server infrastructure, including Windows and Linux systems.',
    tags: ['System Administration', 'Windows Server', 'Linux', 'Virtualization'],
    postedDate: '2024-07-24',
  },
  {
    id: '29',
    title: 'Blockchain Developer',
    companyName: 'Decentralized Future Co.',
    companyLogoUrl: 'https://placehold.co/100x100/6495ED/FFFFFF.png?text=DF',
    dataAihint: 'blockchain tech',
    location: 'Remote',
    salary: '$130,000 - $170,000',
    shortDescription: 'Develop smart contracts and decentralized applications (dApps) on various blockchain platforms.',
    tags: ['Blockchain', 'Solidity', 'Ethereum', 'Smart Contracts', 'dApps'],
    postedDate: '2024-07-21',
  },
  {
    id: '30',
    title: 'Customer Success Manager',
    companyName: 'ClientFocus SaaS',
    companyLogoUrl: 'https://placehold.co/100x100/DB7093/FFFFFF.png?text=CS',
    dataAihint: 'saas company',
    location: 'San Francisco, CA (Hybrid)',
    shortDescription: 'Build strong relationships with clients, ensure their success with our SaaS product, and drive retention.',
    tags: ['Customer Success', 'SaaS', 'Account Management', 'CRM'],
    postedDate: '2024-07-18',
  },
  {
    id: '31',
    title: 'Software Engineer (Java)',
    companyName: 'Enterprise Coder',
    companyLogoUrl: 'https://placehold.co/100x100/f0db4f/000000.png?text=EC',
    dataAihint: 'java development',
    location: 'New York, NY',
    salary: '$110,000 - $140,000',
    shortDescription: 'Develop enterprise-level applications using Java and Spring framework.',
    tags: ['Java', 'Spring', 'Microservices', 'Backend'],
    postedDate: '2024-07-23',
  },
  {
    id: '32',
    title: 'Data Engineer',
    companyName: 'DataFlow Solutions',
    companyLogoUrl: 'https://placehold.co/100x100/00c0ef/FFFFFF.png?text=DF',
    dataAihint: 'data engineering',
    location: 'Seattle, WA',
    shortDescription: 'Build and maintain scalable data pipelines and ETL processes.',
    tags: ['Data Engineering', 'ETL', 'Spark', 'Kafka', 'Python'],
    postedDate: '2024-07-22',
  },
  {
    id: '33',
    title: 'Graphic Designer',
    companyName: 'VisualVibe Studios',
    companyLogoUrl: 'https://placehold.co/100x100/ff69b4/FFFFFF.png?text=VS',
    dataAihint: 'design studio',
    location: 'Remote',
    salary: '$60,000 - $80,000',
    shortDescription: 'Create visually appealing graphics for marketing materials, websites, and social media.',
    tags: ['Graphic Design', 'Adobe Creative Suite', 'Branding', 'Illustration'],
    postedDate: '2024-07-20',
  },
  {
    id: '34',
    title: 'Mobile Developer (Android)',
    companyName: 'DroidWorks Inc.',
    companyLogoUrl: 'https://placehold.co/100x100/a4c639/FFFFFF.png?text=DW',
    dataAihint: 'android development',
    location: 'Mountain View, CA',
    shortDescription: 'Develop and maintain native Android applications using Kotlin and Java.',
    tags: ['Android', 'Kotlin', 'Java', 'Mobile Development'],
    postedDate: '2024-07-18',
  },
  {
    id: '35',
    title: 'SEO Specialist',
    companyName: 'RankUp Digital',
    companyLogoUrl: 'https://placehold.co/100x100/ff8c00/FFFFFF.png?text=RD',
    dataAihint: 'seo agency',
    location: 'Remote',
    salary: '$70,000 - $90,000',
    shortDescription: 'Optimize websites for search engines through keyword research, on-page, and off-page SEO.',
    tags: ['SEO', 'Keyword Research', 'Google Analytics', 'Link Building'],
    postedDate: '2024-07-16',
  },
  {
    id: '36',
    title: 'UI Engineer',
    companyName: 'Interface Masters',
    companyLogoUrl: 'https://placehold.co/100x100/00fa9a/000000.png?text=IM',
    dataAihint: 'ui development',
    location: 'Austin, TX',
    shortDescription: 'Translate UI/UX designs into functional web components and interfaces.',
    tags: ['UI Development', 'HTML', 'CSS', 'JavaScript', 'React'],
    postedDate: '2024-07-24',
  },
  {
    id: '37',
    title: 'Content Marketing Manager',
    companyName: 'EngageContent Pro',
    companyLogoUrl: 'https://placehold.co/100x100/dda0dd/000000.png?text=EC',
    dataAihint: 'content marketing',
    location: 'Remote',
    salary: '$80,000 - $100,000',
    shortDescription: 'Develop and manage content marketing strategies to drive engagement and leads.',
    tags: ['Content Marketing', 'SEO', 'Social Media', 'Strategy'],
    postedDate: '2024-07-17',
  },
  {
    id: '38',
    title: 'Cloud Security Engineer',
    companyName: 'SecureCloud Ltd.',
    companyLogoUrl: 'https://placehold.co/100x100/b0e0e6/000000.png?text=SC',
    dataAihint: 'cloud security',
    location: 'Reston, VA',
    shortDescription: 'Secure cloud environments (AWS, Azure, GCP) and implement security best practices.',
    tags: ['Cloud Security', 'AWS Security', 'Azure Security', 'IAM'],
    postedDate: '2024-07-14',
  },
  {
    id: '39',
    title: 'Technical Support Engineer',
    companyName: 'SolveIT Now',
    companyLogoUrl: 'https://placehold.co/100x100/fafad2/000000.png?text=SN',
    dataAihint: 'tech support',
    location: 'Remote',
    salary: '$65,000 - $85,000',
    shortDescription: 'Provide advanced technical support for enterprise software products.',
    tags: ['Technical Support', 'Troubleshooting', 'Customer Service', 'SQL'],
    postedDate: '2024-07-19',
  },
  {
    id: '40',
    title: 'E-commerce Manager',
    companyName: 'Shopify Gurus',
    companyLogoUrl: 'https://placehold.co/100x100/90ee90/000000.png?text=SG',
    dataAihint: 'ecommerce agency',
    location: 'Miami, FL',
    shortDescription: 'Manage and optimize e-commerce platforms, driving sales and customer experience.',
    tags: ['E-commerce', 'Shopify', 'Digital Marketing', 'Conversion Optimization'],
    postedDate: '2024-07-21',
  },
  {
    id: '41',
    title: 'Software Development Manager',
    companyName: 'CodeLeads Inc.',
    companyLogoUrl: 'https://placehold.co/100x100/add8e6/000000.png?text=CL',
    dataAihint: 'software management',
    location: 'Toronto, Canada',
    salary: '$140,000 - $180,000 CAD',
    shortDescription: 'Lead and mentor a team of software developers, overseeing project delivery and technical excellence.',
    tags: ['Management', 'Software Development', 'Agile', 'Leadership'],
    postedDate: '2024-07-25',
  },
  {
    id: '42',
    title: 'UX Researcher',
    companyName: 'UserFirst Insights',
    companyLogoUrl: 'https://placehold.co/100x100/ffb6c1/000000.png?text=UI',
    dataAihint: 'ux research',
    location: 'Remote',
    shortDescription: 'Conduct user research, usability testing, and analyze user feedback to inform product design.',
    tags: ['UX Research', 'Usability Testing', 'User Interviews', 'Qualitative Research'],
    postedDate: '2024-07-13',
  },
  {
    id: '43',
    title: 'Sales Engineer',
    companyName: 'TechSolutions PreSales',
    companyLogoUrl: 'https://placehold.co/100x100/20b2aa/FFFFFF.png?text=TS',
    dataAihint: 'sales engineering',
    location: 'Chicago, IL',
    salary: '$100,000 - $130,000 + Bonus',
    shortDescription: 'Provide technical expertise during the sales process, demonstrating product capabilities to potential clients.',
    tags: ['Sales Engineering', 'Pre-sales', 'Technical Presentations', 'SaaS'],
    postedDate: '2024-07-20',
  },
  {
    id: '44',
    title: 'Operations Manager',
    companyName: 'Streamline Ops Co.',
    companyLogoUrl: 'https://placehold.co/100x100/7fffd4/000000.png?text=SO',
    dataAihint: 'operations management',
    location: 'Dallas, TX',
    shortDescription: 'Oversee and improve operational processes to enhance efficiency and productivity.',
    tags: ['Operations Management', 'Process Improvement', 'Logistics', 'Supply Chain'],
    postedDate: '2024-07-15',
  },
  {
    id: '45',
    title: 'Firmware Engineer',
    companyName: 'Embedded Innovations',
    companyLogoUrl: 'https://placehold.co/100x100/c71585/FFFFFF.png?text=EI',
    dataAihint: 'embedded systems',
    location: 'San Diego, CA',
    shortDescription: 'Design, develop, and test firmware for embedded systems and IoT devices.',
    tags: ['Firmware', 'Embedded Systems', 'C/C++', 'IoT', 'RTOS'],
    postedDate: '2024-07-22',
  },
  {
    id: '46',
    title: 'Legal Counsel, Technology',
    companyName: 'LexTech Advisors',
    companyLogoUrl: 'https://placehold.co/100x100/deb887/000000.png?text=LT',
    dataAihint: 'legal services',
    location: 'New York, NY (Hybrid)',
    salary: '$150,000 - $200,000',
    shortDescription: 'Provide legal advice on technology-related matters, including contracts, IP, and data privacy.',
    tags: ['Legal', 'Technology Law', 'Contracts', 'Intellectual Property', 'Data Privacy'],
    postedDate: '2024-07-18',
  },
  {
    id: '47',
    title: 'Recruiter (Technical)',
    companyName: 'TalentConnect Tech',
    companyLogoUrl: 'https://placehold.co/100x100/5f9ea0/FFFFFF.png?text=TC',
    dataAihint: 'recruitment agency',
    location: 'Remote',
    shortDescription: 'Source, screen, and recruit top technical talent for various roles.',
    tags: ['Recruitment', 'Technical Recruiting', 'Sourcing', 'Applicant Tracking Systems'],
    postedDate: '2024-07-16',
  },
  {
    id: '48',
    title: 'Business Development Manager',
    companyName: 'GrowthPartners International',
    companyLogoUrl: 'https://placehold.co/100x100/dc143c/FFFFFF.png?text=GP',
    dataAihint: 'business development',
    location: 'London, UK',
    salary: '£70,000 - £90,000 + Commission',
    shortDescription: 'Identify and develop new business opportunities and strategic partnerships.',
    tags: ['Business Development', 'Sales', 'Strategy', 'Partnerships'],
    postedDate: '2024-07-23',
  },
  {
    id: '49',
    title: 'Quantitative Analyst',
    companyName: 'AlphaQuant Strategies',
    companyLogoUrl: 'https://placehold.co/100x100/00ffff/000000.png?text=AQ',
    dataAihint: 'quantitative finance',
    location: 'New York, NY',
    shortDescription: 'Develop and implement quantitative models for trading and risk management.',
    tags: ['Quantitative Finance', 'Python', 'R', 'Statistics', 'Financial Modeling'],
    postedDate: '2024-07-24',
  },
  {
    id: '50',
    title: 'Animator (2D/3D)',
    companyName: 'MotionMasters Studio',
    companyLogoUrl: 'https://placehold.co/100x100/008b8b/FFFFFF.png?text=MM',
    dataAihint: 'animation studio',
    location: 'Burbank, CA',
    salary: '$70,000 - $95,000',
    shortDescription: 'Create high-quality animations for film, television, or games. Proficiency in Maya, Blender, or Toon Boom.',
    tags: ['Animation', '2D Animation', '3D Animation', 'Maya', 'Blender'],
    postedDate: '2024-07-17',
  },
  {
    id: '51',
    title: 'Software Engineer, Backend (Go)',
    companyName: 'GoFast Systems',
    companyLogoUrl: 'https://placehold.co/100x100/00008b/FFFFFF.png?text=GS',
    dataAihint: 'go development',
    location: 'Remote',
    salary: '$120,000 - $150,000',
    shortDescription: 'Develop high-performance backend services using Go (Golang). Experience with microservices and distributed systems.',
    tags: ['Go', 'Golang', 'Backend', 'Microservices', 'Distributed Systems'],
    postedDate: '2024-07-25',
  },
  {
    id: '52',
    title: 'IT Project Manager',
    companyName: 'TechProject Pros',
    companyLogoUrl: 'https://placehold.co/100x100/b8860b/FFFFFF.png?text=TP',
    dataAihint: 'it project management',
    location: 'Washington D.C.',
    shortDescription: 'Manage IT projects from initiation to completion, ensuring they meet scope, budget, and timeline requirements.',
    tags: ['Project Management', 'PMP', 'Agile', 'IT Infrastructure', 'Software Development Lifecycle'],
    postedDate: '2024-07-14',
  },
  {
    id: '53',
    title: 'Data Visualization Specialist',
    companyName: 'InsightVisuals',
    companyLogoUrl: 'https://placehold.co/100x100/006400/FFFFFF.png?text=IV',
    dataAihint: 'data visualization',
    location: 'Boston, MA',
    shortDescription: 'Create compelling data visualizations and dashboards using tools like Tableau, Power BI, or D3.js.',
    tags: ['Data Visualization', 'Tableau', 'Power BI', 'D3.js', 'Business Intelligence'],
    postedDate: '2024-07-19',
  },
  {
    id: '54',
    title: 'Robotics Engineer',
    companyName: 'RoboFuture Dynamics',
    companyLogoUrl: 'https://placehold.co/100x100/bdb76b/000000.png?text=RD',
    dataAihint: 'robotics company',
    location: 'Pittsburgh, PA',
    salary: '$100,000 - $130,000',
    shortDescription: 'Design, build, and test robotic systems. Experience with ROS, C++, and Python.',
    tags: ['Robotics', 'ROS', 'C++', 'Python', 'Automation'],
    postedDate: '2024-07-21',
  },
  {
    id: '55',
    title: 'Social Media Manager',
    companyName: 'BuzzConnect Digital',
    companyLogoUrl: 'https://placehold.co/100x100/8b008b/FFFFFF.png?text=BC',
    dataAihint: 'social media agency',
    location: 'Remote',
    shortDescription: 'Develop and manage social media strategies, create engaging content, and analyze performance.',
    tags: ['Social Media Marketing', 'Content Creation', 'Community Management', 'Analytics'],
    postedDate: '2024-07-23',
  },
  {
    id: '56',
    title: 'Test Automation Architect',
    companyName: 'AutoTest Solutions',
    companyLogoUrl: 'https://placehold.co/100x100/556b2f/FFFFFF.png?text=AS',
    dataAihint: 'test automation',
    location: 'San Francisco, CA',
    salary: '$140,000 - $170,000',
    shortDescription: 'Design and implement test automation frameworks and strategies for large-scale applications.',
    tags: ['Test Automation', 'Architecture', 'Selenium', 'Cypress', 'DevOps'],
    postedDate: '2024-07-16',
  },
  {
    id: '57',
    title: 'Product Owner',
    companyName: 'AgileProduct Hub',
    companyLogoUrl: 'https://placehold.co/100x100/ff8c00/FFFFFF.png?text=AP',
    dataAihint: 'product development',
    location: 'Austin, TX (Hybrid)',
    shortDescription: 'Define and prioritize product backlog items, working closely with development teams and stakeholders.',
    tags: ['Product Owner', 'Agile', 'Scrum', 'Jira', 'User Stories'],
    postedDate: '2024-07-18',
  },
  {
    id: '58',
    title: 'Embedded Software Engineer',
    companyName: 'CoreLogic Devices',
    companyLogoUrl: 'https://placehold.co/100x100/9932cc/FFFFFF.png?text=CD',
    dataAihint: 'embedded devices',
    location: 'Cambridge, MA',
    shortDescription: 'Develop software for embedded systems, including drivers, middleware, and applications.',
    tags: ['Embedded Software', 'C', 'Linux', 'RTOS', 'Microcontrollers'],
    postedDate: '2024-07-20',
  },
  {
    id: '59',
    title: 'Videographer/Editor',
    companyName: 'CineMotion Productions',
    companyLogoUrl: 'https://placehold.co/100x100/8b0000/FFFFFF.png?text=CP',
    dataAihint: 'video production',
    location: 'Los Angeles, CA',
    salary: '$65,000 - $85,000',
    shortDescription: 'Shoot and edit high-quality video content for various platforms. Proficient in Adobe Premiere Pro and After Effects.',
    tags: ['Videography', 'Video Editing', 'Adobe Premiere Pro', 'After Effects', 'Storytelling'],
    postedDate: '2024-07-22',
  },
  {
    id: '60',
    title: 'Security Operations Center (SOC) Analyst',
    companyName: 'CyberDefend Solutions',
    companyLogoUrl: 'https://placehold.co/100x100/e9967a/000000.png?text=CS',
    dataAihint: 'cybersecurity soc',
    location: 'Remote (US-based)',
    shortDescription: 'Monitor security alerts, investigate incidents, and respond to threats within a SOC environment.',
    tags: ['SOC Analyst', 'Cybersecurity', 'SIEM', 'Incident Response', 'Threat Hunting'],
    postedDate: '2024-07-24',
  },
  {
    id: '61',
    title: 'Software Engineer in Test (SDET)',
    companyName: 'TestDriven Tech',
    companyLogoUrl: 'https://placehold.co/100x100/8fbc8f/000000.png?text=TD',
    dataAihint: 'software testing',
    location: 'Seattle, WA',
    salary: '$110,000 - $140,000',
    shortDescription: 'Design, develop, and maintain automated test frameworks and test cases for software applications.',
    tags: ['SDET', 'Test Automation', 'Java', 'Python', 'CI/CD'],
    postedDate: '2024-07-15',
  },
  {
    id: '62',
    title: 'Instructional Designer',
    companyName: 'LearnWell Solutions',
    companyLogoUrl: 'https://placehold.co/100x100/483d8b/FFFFFF.png?text=LS',
    dataAihint: 'e-learning company',
    location: 'Remote',
    shortDescription: 'Design and develop engaging e-learning content and training materials.',
    tags: ['Instructional Design', 'E-learning', 'Articulate Storyline', 'ADDIE', 'Adult Learning'],
    postedDate: '2024-07-17',
  },
  {
    id: '63',
    title: 'ERP Consultant (SAP)',
    companyName: 'EnterpriseFlow Systems',
    companyLogoUrl: 'https://placehold.co/100x100/2f4f4f/FFFFFF.png?text=ES',
    dataAihint: 'erp consulting',
    location: 'Chicago, IL (Travel required)',
    salary: '$90,000 - $120,000',
    shortDescription: 'Implement and configure SAP ERP solutions for clients, specializing in modules like FI/CO or SD/MM.',
    tags: ['SAP', 'ERP', 'Consulting', 'FI/CO', 'SD/MM'],
    postedDate: '2024-07-19',
  },
  {
    id: '64',
    title: 'Biomedical Engineer',
    companyName: 'MediTech Innovations',
    companyLogoUrl: 'https://placehold.co/100x100/00ced1/000000.png?text=MI',
    dataAihint: 'medical technology',
    location: 'Boston, MA',
    shortDescription: 'Design and develop medical devices and equipment. Knowledge of FDA regulations is a plus.',
    tags: ['Biomedical Engineering', 'Medical Devices', 'R&D', 'FDA Regulations'],
    postedDate: '2024-07-21',
  },
  {
    id: '65',
    title: 'Cloud Support Engineer',
    companyName: 'AWS Pro Services',
    companyLogoUrl: 'https://placehold.co/100x100/9400d3/FFFFFF.png?text=AP',
    dataAihint: 'aws support',
    location: 'Remote',
    salary: '$80,000 - $100,000',
    shortDescription: 'Provide technical support for customers using AWS cloud services. AWS certifications preferred.',
    tags: ['Cloud Support', 'AWS', 'Troubleshooting', 'Customer Service', 'Linux'],
    postedDate: '2024-07-23',
  },
  {
    id: '66',
    title: 'Software Engineer, Mobile (React Native)',
    companyName: 'CrossPlatform Devs',
    companyLogoUrl: 'https://placehold.co/100x100/ff1493/FFFFFF.png?text=CP',
    dataAihint: 'mobile development',
    location: 'New York, NY (Hybrid)',
    shortDescription: 'Develop cross-platform mobile applications using React Native.',
    tags: ['React Native', 'Mobile Development', 'JavaScript', 'iOS', 'Android'],
    postedDate: '2024-07-25',
  },
  {
    id: '67',
    title: 'Clinical Research Coordinator',
    companyName: 'HealWell Trials',
    companyLogoUrl: 'https://placehold.co/100x100/00bfff/FFFFFF.png?text=HT',
    dataAihint: 'clinical research',
    location: 'Philadelphia, PA',
    salary: '$60,000 - $75,000',
    shortDescription: 'Coordinate and manage clinical research studies, ensuring compliance with protocols and regulations.',
    tags: ['Clinical Research', 'GCP', 'Healthcare', 'Data Management'],
    postedDate: '2024-07-13',
  },
  {
    id: '68',
    title: 'Geospatial Analyst',
    companyName: 'TerraMap Solutions',
    companyLogoUrl: 'https://placehold.co/100x100/696969/FFFFFF.png?text=TS',
    dataAihint: 'gis company',
    location: 'Denver, CO',
    shortDescription: 'Analyze and interpret geospatial data using GIS software like ArcGIS or QGIS.',
    tags: ['GIS', 'Geospatial Analysis', 'ArcGIS', 'QGIS', 'Remote Sensing'],
    postedDate: '2024-07-16',
  },
  {
    id: '69',
    title: 'Supply Chain Analyst',
    companyName: 'LogiChain Dynamics',
    companyLogoUrl: 'https://placehold.co/100x100/1e90ff/FFFFFF.png?text=LD',
    dataAihint: 'logistics company',
    location: 'Atlanta, GA',
    salary: '$70,000 - $90,000',
    shortDescription: 'Analyze and optimize supply chain processes to improve efficiency and reduce costs.',
    tags: ['Supply Chain', 'Logistics', 'Data Analysis', 'Inventory Management'],
    postedDate: '2024-07-18',
  },
  {
    id: '70',
    title: 'Telecommunications Engineer',
    companyName: 'ConnectSphere Comms',
    companyLogoUrl: 'https://placehold.co/100x100/b22222/FFFFFF.png?text=CC',
    dataAihint: 'telecom company',
    location: 'Dallas, TX',
    shortDescription: 'Design, install, and maintain telecommunications systems, including voice, data, and video networks.',
    tags: ['Telecommunications', 'Networking', 'VoIP', 'Fiber Optics'],
    postedDate: '2024-07-20',
  },
  {
    id: '71',
    title: 'Environmental Scientist',
    companyName: 'EcoSustain Solutions',
    companyLogoUrl: 'https://placehold.co/100x100/228b22/FFFFFF.png?text=ES',
    dataAihint: 'environmental consulting',
    location: 'Portland, OR',
    salary: '$65,000 - $85,000',
    shortDescription: 'Conduct environmental assessments, analyze data, and develop solutions for environmental challenges.',
    tags: ['Environmental Science', 'Sustainability', 'Data Analysis', 'Field Work'],
    postedDate: '2024-07-22',
  },
  {
    id: '72',
    title: 'UX Writer',
    companyName: 'WordFlow UX',
    companyLogoUrl: 'https://placehold.co/100x100/daa520/000000.png?text=WU',
    dataAihint: 'ux writing',
    location: 'Remote',
    shortDescription: 'Craft clear, concise, and user-centered copy for digital products and interfaces.',
    tags: ['UX Writing', 'Content Strategy', 'Microcopy', 'User Experience'],
    postedDate: '2024-07-24',
  },
  {
    id: '73',
    title: 'Automation Engineer (Industrial)',
    companyName: 'RoboTech Industries',
    companyLogoUrl: 'https://placehold.co/100x100/adff2f/000000.png?text=RI',
    dataAihint: 'industrial automation',
    location: 'Detroit, MI',
    salary: '$90,000 - $120,000',
    shortDescription: 'Design and implement automated systems for industrial processes using PLCs, robotics, and SCADA systems.',
    tags: ['Industrial Automation', 'PLC Programming', 'Robotics', 'SCADA', 'Manufacturing'],
    postedDate: '2024-07-15',
  },
  {
    id: '74',
    title: 'DevSecOps Engineer',
    companyName: 'SecurePipe Innovations',
    companyLogoUrl: 'https://placehold.co/100x100/ff69b4/FFFFFF.png?text=SP',
    dataAihint: 'devsecops company',
    location: 'Austin, TX (Hybrid)',
    shortDescription: 'Integrate security practices into the DevOps lifecycle, automating security testing and compliance.',
    tags: ['DevSecOps', 'Cybersecurity', 'CI/CD', 'Automation', 'Cloud Security'],
    postedDate: '2024-07-17',
  },
  {
    id: '75',
    title: 'Mechanical Engineer',
    companyName: 'PrecisionMech Design',
    companyLogoUrl: 'https://placehold.co/100x100/cd853f/FFFFFF.png?text=PM',
    dataAihint: 'mechanical engineering',
    location: 'Houston, TX',
    salary: '$80,000 - $110,000',
    shortDescription: 'Design, develop, and test mechanical components and systems. Proficiency in CAD software required.',
    tags: ['Mechanical Engineering', 'CAD', 'SolidWorks', 'Product Design', 'Manufacturing'],
    postedDate: '2024-07-19',
  },
  {
    id: '76',
    title: 'Research Scientist (Chemistry)',
    companyName: 'ChemMolecular Labs',
    companyLogoUrl: 'https://placehold.co/100x100/4682b4/FFFFFF.png?text=CL',
    dataAihint: 'chemistry lab',
    location: 'San Diego, CA',
    shortDescription: 'Conduct research in chemistry, develop new compounds, and analyze experimental data.',
    tags: ['Chemistry', 'Research', 'Organic Synthesis', 'Analytical Chemistry', 'Lab Work'],
    postedDate: '2024-07-21',
  },
  {
    id: '77',
    title: 'Technical Program Manager',
    companyName: 'ProgramDriven Tech',
    companyLogoUrl: 'https://placehold.co/100x100/d2691e/FFFFFF.png?text=PD',
    dataAihint: 'program management',
    location: 'Seattle, WA',
    salary: '$130,000 - $160,000',
    shortDescription: 'Manage complex technical programs, coordinating cross-functional teams to deliver results.',
    tags: ['Program Management', 'Technical Leadership', 'Agile', 'Stakeholder Management'],
    postedDate: '2024-07-23',
  },
  {
    id: '78',
    title: 'Actuary',
    companyName: 'RiskSolve Analytics',
    companyLogoUrl: 'https://placehold.co/100x100/9acd32/000000.png?text=RA',
    dataAihint: 'actuarial science',
    location: 'Hartford, CT',
    shortDescription: 'Analyze financial risks using mathematics, statistics, and financial theory. Actuarial exams preferred.',
    tags: ['Actuarial Science', 'Risk Management', 'Statistics', 'Financial Modeling', 'Insurance'],
    postedDate: '2024-07-25',
  },
  {
    id: '79',
    title: '3D Modeler/Artist',
    companyName: 'DimensionCraft Studios',
    companyLogoUrl: 'https://placehold.co/100x100/6a5acd/FFFFFF.png?text=DS',
    dataAihint: '3d modeling studio',
    location: 'Remote',
    salary: '$60,000 - $80,000',
    shortDescription: 'Create high-quality 3D models for games, animation, or visualization. Proficiency in Maya, Blender, or ZBrush.',
    tags: ['3D Modeling', 'Texturing', 'Maya', 'Blender', 'ZBrush'],
    postedDate: '2024-07-13',
  },
  {
    id: '80',
    title: 'Machine Learning Operations (MLOps) Engineer',
    companyName: 'AIOps Flow',
    companyLogoUrl: 'https://placehold.co/100x100/ba55d3/FFFFFF.png?text=AF',
    dataAihint: 'mlops company',
    location: 'San Francisco, CA (Hybrid)',
    shortDescription: 'Build and manage infrastructure for deploying, monitoring, and scaling machine learning models.',
    tags: ['MLOps', 'Machine Learning', 'DevOps', 'Kubernetes', 'Cloud'],
    postedDate: '2024-07-16',
  },
  {
    id: '81',
    title: 'Electrical Engineer',
    companyName: 'ElectroCircuit Design',
    companyLogoUrl: 'https://placehold.co/100x100/ffdab9/000000.png?text=ED',
    dataAihint: 'electrical engineering',
    location: 'Austin, TX',
    salary: '$85,000 - $115,000',
    shortDescription: 'Design, develop, and test electrical systems and components. Experience with PCB design and power electronics.',
    tags: ['Electrical Engineering', 'PCB Design', 'Power Electronics', 'Circuit Design'],
    postedDate: '2024-07-18',
  },
  {
    id: '82',
    title: 'Public Relations Specialist',
    companyName: 'MediaConnect PR',
    companyLogoUrl: 'https://placehold.co/100x100/f0e68c/000000.png?text=MC',
    dataAihint: 'pr agency',
    location: 'New York, NY',
    shortDescription: 'Manage media relations, develop PR campaigns, and enhance brand reputation.',
    tags: ['Public Relations', 'Media Relations', 'Communications', 'Press Releases'],
    postedDate: '2024-07-20',
  },
  {
    id: '83',
    title: 'Site Reliability Engineer (SRE)',
    companyName: 'ReliabilityFirst Cloud',
    companyLogoUrl: 'https://placehold.co/100x100/add8e6/000000.png?text=RF',
    dataAihint: 'sre company',
    location: 'Remote',
    salary: '$125,000 - $160,000',
    shortDescription: 'Ensure the reliability, scalability, and performance of large-scale systems. Focus on automation and monitoring.',
    tags: ['SRE', 'DevOps', 'Cloud Infrastructure', 'Monitoring', 'Automation', 'Kubernetes'],
    postedDate: '2024-07-22',
  },
  {
    id: '84',
    title: 'Pharmacist',
    companyName: 'HealthWell Pharmacy',
    companyLogoUrl: 'https://placehold.co/100x100/90ee90/000000.png?text=HP',
    dataAihint: 'pharmacy',
    location: 'Chicago, IL',
    shortDescription: 'Dispense medications, counsel patients on drug use, and manage pharmacy operations. PharmD required.',
    tags: ['Pharmacist', 'Healthcare', 'Medication Management', 'Patient Counseling'],
    postedDate: '2024-07-24',
  },
  {
    id: '85',
    title: 'Aerospace Engineer',
    companyName: 'AstroSpace Dynamics',
    companyLogoUrl: 'https://placehold.co/100x100/dda0dd/000000.png?text=AD',
    dataAihint: 'aerospace company',
    location: 'Huntsville, AL',
    salary: '$90,000 - $120,000',
    shortDescription: 'Design, develop, and test aircraft, spacecraft, and related systems. Experience with aerodynamics and propulsion.',
    tags: ['Aerospace Engineering', 'Aerodynamics', 'Propulsion', 'Systems Engineering'],
    postedDate: '2024-07-14',
  },
  {
    id: '86',
    title: 'Interior Designer',
    companyName: 'SpaceCraft Interiors',
    companyLogoUrl: 'https://placehold.co/100x100/b0e0e6/000000.png?text=SI',
    dataAihint: 'interior design firm',
    location: 'Miami, FL',
    shortDescription: 'Create functional and aesthetically pleasing interior spaces for residential or commercial clients. Portfolio required.',
    tags: ['Interior Design', 'Space Planning', 'AutoCAD', 'SketchUp', 'Client Management'],
    postedDate: '2024-07-17',
  },
  {
    id: '87',
    title: 'Biostatistician',
    companyName: 'StatsLife Sciences',
    companyLogoUrl: 'https://placehold.co/100x100/ffc0cb/000000.png?text=SL',
    dataAihint: 'biostatistics company',
    location: 'Boston, MA (Hybrid)',
    salary: '$95,000 - $125,000',
    shortDescription: 'Apply statistical methods to design and analyze clinical trials and biomedical research data.',
    tags: ['Biostatistics', 'Clinical Trials', 'SAS', 'R', 'Statistical Analysis'],
    postedDate: '2024-07-19',
  },
  {
    id: '88',
    title: 'Food Scientist',
    companyName: 'NutriTaste Innovations',
    companyLogoUrl: 'https://placehold.co/100x100/f5deb3/000000.png?text=NI',
    dataAihint: 'food science company',
    location: 'Chicago, IL',
    shortDescription: 'Conduct research and development for new food products, focusing on quality, safety, and nutrition.',
    tags: ['Food Science', 'Product Development', 'Quality Control', 'Sensory Analysis'],
    postedDate: '2024-07-21',
  },
  {
    id: '89',
    title: 'Technical Artist (Games)',
    companyName: 'PixelPipe Studios',
    companyLogoUrl: 'https://placehold.co/100x100/7b68ee/FFFFFF.png?text=PS',
    dataAihint: 'game development studio',
    location: 'Austin, TX',
    salary: '$80,000 - $110,000',
    shortDescription: 'Bridge the gap between art and programming in game development, creating tools and optimizing pipelines.',
    tags: ['Technical Art', 'Game Development', 'Shaders', 'Scripting', 'Unity', 'Unreal Engine'],
    postedDate: '2024-07-23',
  },
  {
    id: '90',
    title: 'Marine Biologist',
    companyName: 'OceanGuard Research',
    companyLogoUrl: 'https://placehold.co/100x100/40e0d0/000000.png?text=OR',
    dataAihint: 'marine research institute',
    location: 'San Diego, CA (Field work involved)',
    shortDescription: 'Study marine organisms and ecosystems, conduct research, and contribute to conservation efforts.',
    tags: ['Marine Biology', 'Oceanography', 'Research', 'Conservation', 'Field Work'],
    postedDate: '2024-07-25',
  },
  {
    id: '91',
    title: 'Civil Engineer',
    companyName: 'InfraBuild Solutions',
    companyLogoUrl: 'https://placehold.co/100x100/c0c0c0/000000.png?text=IS',
    dataAihint: 'civil engineering firm',
    location: 'Denver, CO',
    salary: '$75,000 - $100,000',
    shortDescription: 'Design, construct, and maintain infrastructure projects like roads, bridges, and buildings. PE license preferred.',
    tags: ['Civil Engineering', 'Structural Design', 'AutoCAD', 'Construction Management'],
    postedDate: '2024-07-13',
  },
  {
    id: '92',
    title: 'Technical Recruiter (Sourcer)',
    companyName: 'SourcePro Talent',
    companyLogoUrl: 'https://placehold.co/100x100/87cefa/000000.png?text=ST',
    dataAihint: 'talent sourcing',
    location: 'Remote',
    shortDescription: 'Specialize in identifying and engaging passive technical candidates for hard-to-fill roles.',
    tags: ['Sourcing', 'Technical Recruiting', 'Boolean Search', 'Candidate Engagement'],
    postedDate: '2024-07-15',
  },
  {
    id: '93',
    title: 'Sustainability Manager',
    companyName: 'GreenFuture Corp',
    companyLogoUrl: 'https://placehold.co/100x100/3cb371/FFFFFF.png?text=GC',
    dataAihint: 'sustainability consulting',
    location: 'San Francisco, CA',
    salary: '$90,000 - $120,000',
    shortDescription: 'Develop and implement sustainability strategies, manage ESG reporting, and promote environmental initiatives.',
    tags: ['Sustainability', 'ESG', 'Corporate Social Responsibility', 'Environmental Management'],
    postedDate: '2024-07-17',
  },
  {
    id: '94',
    title: 'Chemical Engineer',
    companyName: 'ChemProcess Solutions',
    companyLogoUrl: 'https://placehold.co/100x100/ff7f50/FFFFFF.png?text=CS',
    dataAihint: 'chemical processing',
    location: 'Houston, TX',
    shortDescription: 'Design and optimize chemical processes and equipment for manufacturing plants.',
    tags: ['Chemical Engineering', 'Process Design', 'Aspen Plus', 'Manufacturing'],
    postedDate: '2024-07-19',
  },
  {
    id: '95',
    title: 'Grant Writer',
    companyName: 'FundingSecure Non-Profit',
    companyLogoUrl: 'https://placehold.co/100x100/6495ed/FFFFFF.png?text=FS',
    dataAihint: 'nonprofit organization',
    location: 'Remote',
    salary: '$55,000 - $75,000',
    shortDescription: 'Research, write, and submit grant proposals to secure funding for non-profit initiatives.',
    tags: ['Grant Writing', 'Non-profit', 'Fundraising', 'Proposal Writing'],
    postedDate: '2024-07-21',
  },
  {
    id: '96',
    title: 'Logistics Coordinator',
    companyName: 'ShipItFast Logistics',
    companyLogoUrl: 'https://placehold.co/100x100/deb887/000000.png?text=SL',
    dataAihint: 'logistics and shipping',
    location: 'Chicago, IL',
    shortDescription: 'Coordinate and manage transportation, warehousing, and inventory for efficient supply chain operations.',
    tags: ['Logistics', 'Supply Chain', 'Transportation', 'Inventory Management', 'Coordination'],
    postedDate: '2024-07-23',
  },
  {
    id: '97',
    title: 'Astronomer',
    companyName: 'Celestial Observatory Institute',
    companyLogoUrl: 'https://placehold.co/100x100/000080/FFFFFF.png?text=CO',
    dataAihint: 'astronomy research',
    location: 'Pasadena, CA (Research facility)',
    salary: '$80,000 - $110,000',
    shortDescription: 'Conduct astronomical research, analyze observational data, and publish findings. PhD typically required.',
    tags: ['Astronomy', 'Astrophysics', 'Research', 'Data Analysis', 'Telescopes'],
    postedDate: '2024-07-25',
  },
  {
    id: '98',
    title: 'Chief Financial Officer (CFO)',
    companyName: 'FinGrowth Startups',
    companyLogoUrl: 'https://placehold.co/100x100/2e8b57/FFFFFF.png?text=FS',
    dataAihint: 'finance leadership',
    location: 'New York, NY',
    shortDescription: 'Lead the financial strategy and operations of a growing startup. Extensive experience required.',
    tags: ['CFO', 'Finance', 'Strategy', 'Leadership', 'Startups', 'Venture Capital'],
    postedDate: '2024-07-12',
  },
  {
    id: '99',
    title: 'Urban Planner',
    companyName: 'CityScape Design Group',
    companyLogoUrl: 'https://placehold.co/100x100/a9a9a9/000000.png?text=CD',
    dataAihint: 'urban planning firm',
    location: 'Portland, OR',
    salary: '$70,000 - $90,000',
    shortDescription: 'Develop plans and programs for the use of land and resources in urban and regional areas.',
    tags: ['Urban Planning', 'GIS', 'Community Development', 'Policy Analysis'],
    postedDate: '2024-07-16',
  },
  {
    id: '100',
    title: 'Veterinarian',
    companyName: 'PawsWell Animal Clinic',
    companyLogoUrl: 'https://placehold.co/100x100/d8bfd8/000000.png?text=PA',
    dataAihint: 'animal clinic',
    location: 'Austin, TX',
    shortDescription: 'Provide medical and surgical care for animals. DVM degree and state license required.',
    tags: ['Veterinary Medicine', 'Animal Health', 'Surgery', 'Diagnostics'],
    postedDate: '2024-07-18',
  }
];

export const placeholderApplications: Application[] = [
  {
    id: 'app1',
    jobTitle: 'Software Engineer, Frontend',
    companyName: 'Innovatech Solutions',
    status: 'Interviewing',
    appliedDate: '2024-07-15',
    jobId: '1',
  },
  {
    id: 'app2',
    jobTitle: 'Product Manager',
    companyName: 'FutureGadgets Inc.',
    status: 'Applied',
    appliedDate: '2024-07-19',
    jobId: '2',
  },
  {
    id: 'app3',
    jobTitle: 'UX/UI Designer',
    companyName: 'Creative Minds Co.',
    status: 'Offer',
    appliedDate: '2024-07-10',
    jobId: '3',
  },
];
